import CONVERSION from '../data/scriptConversion.json'
import type { ScriptMode } from '../types'

/*
 * Traditional → simplified, for showing traditional-authored text to a learner
 * who reads simplified.
 *
 * The reading library is the only place this is needed. Story prose is authored
 * and stored canonically in traditional (`src/data/stories.ts`), and that stays
 * true — this converts the *display* form and nothing else. Everywhere the app
 * shows a word out of the bank it already has both forms and uses `displayWord`
 * instead; nothing here should be reached for that.
 *
 * ── Why a character map is enough here, and only in this direction ───────────
 *
 * Script conversion is famously not one-to-one, but the ambiguity is almost
 * entirely in the *other* direction: simplified 干 stands for 乾, 幹 and 干, and
 * choosing between them needs the surrounding word. Traditional → simplified,
 * each traditional character has essentially one simplified form. That is why
 * this table exists and why there is deliberately no simp → trad counterpart —
 * a per-character map going that way would be wrong often enough to matter.
 *
 * It is also only half the story reader's conversion, and the smaller half.
 * `segmentText` matches prose against the word bank first and takes each matched
 * word's own `simplified` field — CC-CEDICT's phrase-level answer, and the same
 * data the dictionary shows. That covers 92% of the Han characters in the
 * library. This table handles what is left: 117 character occurrences across all
 * 103 story pages, all of them unambiguous single characters.
 *
 * The table is generated by `scripts/buildWordBank.mjs` from CC-CEDICT's own
 * single-character entries, so it cannot disagree with the word bank about a
 * character the two both know. That matters more than it sounds: if conversion
 * came from some other source, a tapped word's displayed form could differ from
 * its own dictionary entry's simplified form.
 */

/** Lazily built, because a simplified learner is not the common case. */
let tradToSimp: Map<string, string> | null = null

function table(): Map<string, string> {
  if (tradToSimp) return tradToSimp
  tradToSimp = new Map()
  const from = [...CONVERSION.traditional]
  const to = [...CONVERSION.simplified]
  for (let i = 0; i < from.length; i++) tradToSimp.set(from[i], to[i])
  return tradToSimp
}

/**
 * Traditional text, one character at a time.
 *
 * Character count is preserved — guaranteed by the build, which fails rather
 * than emit a pair whose two forms differ in length. The story reader relies on
 * that: the narration cursor and `segmentSpans` both measure offsets against the
 * canonical text, so a conversion that changed length would slide the green
 * highlight out of step with the words under it.
 */
export function toSimplifiedText(text: string): string {
  const map = table()
  let out = ''
  for (const character of text) out += map.get(character) ?? character
  return out
}

/**
 * Canonical traditional text as the learner should see it.
 *
 * The identity function for a traditional learner, so callers can hand it every
 * string unconditionally rather than branching at each one.
 */
export function forScript(canonicalTraditional: string, script: ScriptMode): string {
  return script === 'simplified' ? toSimplifiedText(canonicalTraditional) : canonicalTraditional
}
