import '../global.css'
import { useEffect } from 'react'
import { Stack, Redirect, usePathname } from 'expo-router'
import { GestureHandlerRootView } from 'react-native-gesture-handler'
import { SafeAreaProvider } from 'react-native-safe-area-context'
import * as SplashScreen from 'expo-splash-screen'
import { StatusBar } from 'expo-status-bar'
import { useFonts } from 'expo-font'
/*
 * Fonts are imported one weight at a time, from each package's per-weight
 * subpath, and must stay that way. Every @expo-google-fonts package's root
 * index.js `require`s all of its weights, so importing from the package root
 * makes Metro bundle every one of them — all 8 weights of Noto Serif SC
 * (113MB) to register 4, all 9 of Noto Sans TC (61MB) to register 3. Naming
 * the weight's own directory pulls in that .ttf alone.
 *
 * The registrations below are unchanged by this: same families, same weights,
 * same faces. What stops being bundled is 145MB of .ttf that nothing loads.
 * Adding a weight means adding its subpath import, never widening one back to
 * the package root.
 */
import { Nunito_400Regular } from '@expo-google-fonts/nunito/400Regular'
import { Nunito_600SemiBold } from '@expo-google-fonts/nunito/600SemiBold'
import { Nunito_700Bold } from '@expo-google-fonts/nunito/700Bold'
import { Nunito_800ExtraBold } from '@expo-google-fonts/nunito/800ExtraBold'
import { Nunito_900Black } from '@expo-google-fonts/nunito/900Black'
import { NunitoSans_400Regular } from '@expo-google-fonts/nunito-sans/400Regular'
import { NunitoSans_600SemiBold } from '@expo-google-fonts/nunito-sans/600SemiBold'
import { NunitoSans_700Bold } from '@expo-google-fonts/nunito-sans/700Bold'
import { NunitoSans_800ExtraBold } from '@expo-google-fonts/nunito-sans/800ExtraBold'
import { Caveat_500Medium } from '@expo-google-fonts/caveat/500Medium'
import { Caveat_700Bold } from '@expo-google-fonts/caveat/700Bold'
import { Kalam_700Bold } from '@expo-google-fonts/kalam/700Bold'
/*
 * The eleven CJK faces come from src/assets/fonts, not from their packages.
 *
 * They are the same Noto faces, subset to the 13,349 characters this app can
 * actually display — a full Noto CJK face carries ~31,000 glyphs, and the rest
 * was 58MB of weight nobody's phone would ever draw. Generated by
 * scripts/subsetFonts.py from the corpus that scripts/buildCharacterCorpus.mjs
 * derives from the dictionary, the stroke data, the stories and every source
 * file. That script re-opens each output, reads its cmap, and fails rather than
 * emit a face that lost a character the original could draw — so these are
 * verified, not merely generated. Re-run both after the word bank or the
 * stories change.
 *
 * The Latin families below are still imported from their packages: 3.3MB
 * together, where subsetting would risk a missing glyph for no real saving.
 */
const NotoSerifSC_400Regular = require('../assets/fonts/NotoSerifSC_400Regular.ttf')
const NotoSerifSC_500Medium = require('../assets/fonts/NotoSerifSC_500Medium.ttf')
const NotoSerifSC_600SemiBold = require('../assets/fonts/NotoSerifSC_600SemiBold.ttf')
const NotoSerifSC_700Bold = require('../assets/fonts/NotoSerifSC_700Bold.ttf')
const NotoSansTC_400Regular = require('../assets/fonts/NotoSansTC_400Regular.ttf')
const NotoSansTC_500Medium = require('../assets/fonts/NotoSansTC_500Medium.ttf')
const NotoSansTC_700Bold = require('../assets/fonts/NotoSansTC_700Bold.ttf')
const NotoSerifTC_400Regular = require('../assets/fonts/NotoSerifTC_400Regular.ttf')
const NotoSerifTC_500Medium = require('../assets/fonts/NotoSerifTC_500Medium.ttf')
const NotoSerifTC_600SemiBold = require('../assets/fonts/NotoSerifTC_600SemiBold.ttf')
const NotoSerifTC_700Bold = require('../assets/fonts/NotoSerifTC_700Bold.ttf')
import { Inter_400Regular } from '@expo-google-fonts/inter/400Regular'
import { Inter_500Medium } from '@expo-google-fonts/inter/500Medium'
import { Inter_600SemiBold } from '@expo-google-fonts/inter/600SemiBold'
import { Inter_700Bold } from '@expo-google-fonts/inter/700Bold'
import { Lora_400Regular } from '@expo-google-fonts/lora/400Regular'
import { AppProvider, useApp } from '../context/AppContext'
import { AuthProvider, useAuth } from '../context/AuthContext'
import { AdsProvider } from '../context/AdsContext'
import { TourOverlay } from '../components/tour/TourOverlay'
import { useSubscribePrompt } from '../components/subscription/useSubscribePrompt'
import { configureAudioSession } from '../lib/sound'

SplashScreen.preventAutoHideAsync().catch(() => {})

function RootNavigator() {
  const { ready, onboardingComplete } = useApp()
  /*
   * Held alongside `ready` rather than awaited separately: reading the stored
   * session is an AsyncStorage read, exactly like the rest of hydration, so it
   * costs nothing to wait for and spares the app a frame of signed-out UI
   * before the session lands. Nothing here touches the network — the splash
   * screen must never depend on a request.
   */
  const { ready: authReady } = useAuth()
  const pathname = usePathname()
  const [fontsLoaded] = useFonts({
    Nunito: Nunito_400Regular,
    // Only the bold face is loaded — the greeting is the sole place it's used.
    Caveat: Caveat_700Bold,
    NotoSerifSC: NotoSerifSC_400Regular,
    NotoSerifTC: NotoSerifTC_400Regular,
    // Real bold faces — CJK has no synthesisable bold, so `fontWeight` alone
    // leaves characters looking thin. Used via the `font-hanzi-bold` family.
    NotoSerifSCBold: NotoSerifSC_700Bold,
    NotoSerifTCBold: NotoSerifTC_700Bold,

    // Reading Library / Story Reader faces. RN selects a weight by picking a
    // different family, so each one is registered separately — see the
    // `fontFamily` block in tailwind.config.js for the class names these back.
    NunitoSemiBold: Nunito_600SemiBold,
    NunitoBold: Nunito_700Bold,
    // The Challenges screen's headings. Its spec asks for ExtraBold on titles
    // and Black nowhere — 900 is heavy enough that everything important stops
    // looking important.
    NunitoExtraBold: Nunito_800ExtraBold,
    NunitoBlack: Nunito_900Black,
    Inter: Inter_400Regular,
    InterMedium: Inter_500Medium,
    InterSemiBold: Inter_600SemiBold,
    InterBold: Inter_700Bold,
    Lora: Lora_400Regular,
    // Noto *Sans* TC — the writing guide sets its Chinese UI text (part labels,
    // radical examples) in a sans to sit with Nunito, where the reader and
    // dictionary use the serif. A different typeface, so registered separately.
    NotoSansTC: NotoSansTC_400Regular,
    NotoSansTCMedium: NotoSansTC_500Medium,
    NotoSansTCBold: NotoSansTC_700Bold,

    NotoSerifTCMedium: NotoSerifTC_500Medium,
    NotoSerifTCSemiBold: NotoSerifTC_600SemiBold,
    // The simplified counterparts, for surfaces that follow `settings.script`
    // rather than always rendering traditional — see `hanziFont` in lib/hanzi.ts.
    // Medium is the story reader's prose weight, mirroring NotoSerifTCMedium.
    NotoSerifSCMedium: NotoSerifSC_500Medium,
    NotoSerifSCSemiBold: NotoSerifSC_600SemiBold,
    CaveatMedium: Caveat_500Medium,
    /*
     * The Dashboard's handwritten learner name. Kalam rather than the Caveat
     * above: Caveat is a connected, slanted script, where the reference's name
     * is an upright marker hand with even stroke weight — at 33pt over a gold
     * brush stroke the difference is the whole character of the greeting.
     */
    KalamBold: Kalam_700Bold,

    // Dictionary faces. Nunito *Sans*, not the rounded Nunito the rest of the app
    // uses — a separate typeface, registered per weight for the same reason as
    // everything above.
    NunitoSans: NunitoSans_400Regular,
    NunitoSansSemiBold: NunitoSans_600SemiBold,
    NunitoSansBold: NunitoSans_700Bold,
    NunitoSansExtraBold: NunitoSans_800ExtraBold,
  })

  // One-time audio session setup. Without it, iOS mutes every effect whenever
  // the ring/silent switch is on.
  useEffect(() => {
    configureAudioSession()
  }, [])

  /*
   * The recurring ad-free offer. It lives up here rather than on a screen for
   * the same reason the tour overlay does: it has to outlive whichever screen
   * the learner happens to be on. It does nothing at all once the subscription
   * is active, and nothing during onboarding, a lesson or a review — see the
   * hook.
   */
  useSubscribePrompt()

  useEffect(() => {
    if (ready && fontsLoaded && authReady) SplashScreen.hideAsync().catch(() => {})
  }, [ready, fontsLoaded, authReady])

  if (!ready || !fontsLoaded || !authReady) return null

  if (!onboardingComplete && pathname !== '/onboarding') {
    return <Redirect href="/onboarding" />
  }

  return (
    <>
      <StatusBar style="auto" />
      <Stack screenOptions={{ headerShown: false }} />
      {/*
        Above the navigator, so Shifu stays put across every screen the tour
        walks through instead of being unmounted at each move. It draws nothing
        when no tour is running.
      */}
      <TourOverlay />
    </>
  )
}

export default function RootLayout() {
  return (
    <GestureHandlerRootView style={{ flex: 1 }}>
      <SafeAreaProvider>
        {/*
          Auth wraps the app store, not the other way round: the sync layer
          lives inside AppContext and needs to know which user it is syncing
          for, so the session has to be readable from in there.
        */}
        <AuthProvider>
          <AppProvider>
            {/*
              Ads sit inside the app store because that is where `isAdFree`
              lives, and the ad layer derives from it rather than keeping a
              premium flag of its own — one entitlement, one answer. Inside the
              navigator's parent rather than around it so a banner is always
              below the navigation tree it belongs to.
            */}
            <AdsProvider>
              <RootNavigator />
            </AdsProvider>
          </AppProvider>
        </AuthProvider>
      </SafeAreaProvider>
    </GestureHandlerRootView>
  )
}
