/*
 * Splits src/assets/hanziData.json into src/assets/hanzi/shard-NN.hanzishard,
 * plus a generated index that hands Metro the asset references.
 *
 * ── Why ──────────────────────────────────────────────────────────────────────
 * `hanziData.json` is 15.8MB of source that compiles to 25.8MB of Hermes
 * bytecode — 59% of the whole JS bundle — because Metro inlines an imported
 * .json into the module graph and Hermes then emits construction bytecode for
 * every nested array in it (the `medians` are arrays of [x,y] pairs, which is
 * what makes it *grow* by 1.63x rather than shrink).
 *
 * A `.hanzishard` file is not a source extension, so Metro treats it as an
 * asset: `require()` yields a reference, the bytes ride along in the app rather
 * than in the bundle, and they are read at runtime only for the characters
 * somebody actually draws. The data is unchanged and still ships offline — it
 * moves out of the JS bundle, it does not leave the app.
 *
 * ── Sharding ─────────────────────────────────────────────────────────────────
 * Bucket is `codePointAt(0) % SHARD_COUNT`, which needs no index at runtime: the
 * loader computes the shard from the character itself. That deliberately does
 * not group related characters together — a two-character word may touch two
 * shards — but the alternative (grouping by frequency, or by radical) needs a
 * character->shard map at runtime, which is another table to bundle and keep in
 * step. Modulo spreads 5,378 characters evenly, so no shard is much larger than
 * the average and a miss costs one small read.
 *
 * Re-run after buildHanziData.mjs, alongside buildStrokeCounts.mjs. Idempotent.
 */
import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync, readdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve, join } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const SOURCE = resolve(here, '../src/assets/hanziData.json')
const OUT_DIR = resolve(here, '../src/assets/hanzi')
const INDEX = join(OUT_DIR, 'shards.ts')

/** Keep in step with SHARD_COUNT in src/lib/hanziStrokeData.ts. */
const SHARD_COUNT = 64
const EXT = 'hanzishard'

const data = JSON.parse(readFileSync(SOURCE, 'utf8'))

// A clean rebuild, so a shrinking dataset can't leave a stale shard behind for
// the generated index to keep requiring.
if (existsSync(OUT_DIR)) {
  for (const f of readdirSync(OUT_DIR)) {
    if (f.endsWith(`.${EXT}`) || f === 'shards.ts') rmSync(join(OUT_DIR, f))
  }
}
mkdirSync(OUT_DIR, { recursive: true })

/** @type {Record<string, unknown>[]} */
const buckets = Array.from({ length: SHARD_COUNT }, () => ({}))

let characters = 0
for (const [character, record] of Object.entries(data)) {
  const cp = character.codePointAt(0)
  if (cp === undefined) throw new Error(`Empty key in hanziData.json`)
  buckets[cp % SHARD_COUNT][character] = record
  characters += 1
}

const pad = (n) => String(n).padStart(2, '0')
const sizes = []

for (let i = 0; i < SHARD_COUNT; i++) {
  const file = join(OUT_DIR, `shard-${pad(i)}.${EXT}`)
  const json = JSON.stringify(buckets[i])
  writeFileSync(file, json, 'utf8')
  sizes.push({ shard: i, keys: Object.keys(buckets[i]).length, bytes: Buffer.byteLength(json) })
}

const requires = sizes.map(({ shard }) => `  require('./shard-${pad(shard)}.${EXT}'),`).join('\n')

writeFileSync(
  INDEX,
  `/*
 * GENERATED by scripts/buildHanziShards.mjs — do not edit.
 *
 * The require() table for the stroke-data shards. Each entry is a Metro asset
 * reference, not the data: the bytes stay out of the JS bundle and are read at
 * runtime by lib/hanziStrokeData.ts. Requires are static because Metro resolves
 * them at build time; a computed require would resolve to nothing.
 */

export const SHARD_COUNT = ${SHARD_COUNT}

export const HANZI_SHARDS: number[] = [
${requires}
]
`,
  'utf8',
)

const total = sizes.reduce((n, s) => n + s.bytes, 0)
const largest = sizes.reduce((a, b) => (b.bytes > a.bytes ? b : a))
const smallest = sizes.reduce((a, b) => (b.bytes < a.bytes ? b : a))

console.log(`${characters} characters -> ${SHARD_COUNT} shards, ${(total / 1024 / 1024).toFixed(2)} MB total`)
console.log(`  average ${(total / SHARD_COUNT / 1024).toFixed(1)} KB/shard`)
console.log(`  largest shard-${pad(largest.shard)} ${(largest.bytes / 1024).toFixed(1)} KB (${largest.keys} chars)`)
console.log(`  smallest shard-${pad(smallest.shard)} ${(smallest.bytes / 1024).toFixed(1)} KB (${smallest.keys} chars)`)
