// hanzi-writer's dist bundle is a browser UMD build (window.HanziWriter) — it can
// only run inside a real DOM, so HanziStage embeds it in a WebView rather than
// importing the npm package on the RN side. Metro has no "import raw JS as text"
// mechanism, so this copies the minified bundle into a TS module exporting it as
// a string constant, which writerHtml.ts then embeds into the WebView's HTML.
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const SRC = join(import.meta.dirname, '..', 'node_modules', 'hanzi-writer', 'dist', 'hanzi-writer.min.js')
const OUT = join(import.meta.dirname, '..', 'src', 'components', 'HanziStage', 'hanziWriterEngine.ts')

const source = readFileSync(SRC, 'utf-8')

writeFileSync(
  OUT,
  `// AUTO-GENERATED by scripts/embedHanziWriterEngine.mjs from node_modules/hanzi-writer/dist/hanzi-writer.min.js — do not hand-edit.\nexport const HANZI_WRITER_ENGINE_JS = ${JSON.stringify(source)}\n`,
  'utf-8',
)
console.log(`Wrote ${OUT} (${source.length} bytes embedded)`)
